package handler

import (
	"context"
	"encoding/json"
	"net/http"
	"strings"
	"text/template"
	"time"

	"github.com/vikyarifian/farahdin-go/internal/http/response"
	"github.com/vikyarifian/farahdin-go/web"
	"github.com/vikyarifian/farahdin-go/web/templates/pages"
)

// staticHandler serves embedded assets. Content-hashed URLs (?v=) are
// immutable; anything else must be revalidated.
func staticHandler() http.Handler {
	fs := http.StripPrefix("/static/", http.FileServerFS(web.Static))
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch {
		case r.URL.Query().Get("v") != "":
			w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		case strings.HasPrefix(r.URL.Path, "/static/fonts/"):
			// Fonts are requested by app.css without a version query; a font change gets a new file name.
			w.Header().Set("Cache-Control", "public, max-age=2592000")
		default:
			w.Header().Set("Cache-Control", "no-cache")
		}
		fs.ServeHTTP(w, r)
	})
}

// manifest is the Web App Manifest, built from the source app.json
// (name, portrait orientation, #231d32 background, logo icon).
func (a *App) manifest(w http.ResponseWriter, r *http.Request) {
	m := map[string]any{
		"id":               "/",
		"name":             "Farahdin",
		"short_name":       "Farahdin",
		"description":      "Primbon, horoscope, tarot, clairvoyance and matrix destiny.",
		"start_url":        "/",
		"scope":            "/",
		"display":          "standalone",
		"orientation":      "portrait",
		"background_color": "#231d32",
		"theme_color":      "#231d32",
		"categories":       []string{"lifestyle", "entertainment"},
		"icons": []map[string]string{
			{"src": web.Asset("icons/icon-192.png"), "sizes": "192x192", "type": "image/png", "purpose": "any"},
			{"src": web.Asset("icons/icon-512.png"), "sizes": "512x512", "type": "image/png", "purpose": "any"},
			{"src": web.Asset("icons/icon-maskable-512.png"), "sizes": "512x512", "type": "image/png", "purpose": "maskable"},
		},
	}
	w.Header().Set("Content-Type", "application/manifest+json")
	w.Header().Set("Cache-Control", "no-cache")
	json.NewEncoder(w).Encode(m)
}

// swTemplate is the service worker. See docs/pwa-strategy.md for the policy:
// static assets cache-first (content-hashed), navigations network-only with
// an offline fallback, nothing authenticated is ever cached.
var swTemplate = template.Must(template.New("sw").Parse(`// Farahdin service worker — generated by the server, version {{.Version}}.
const CACHE = "farahdin-static-{{.Version}}";
const OFFLINE_URL = "/offline";
const PRECACHE = {{.Precache}};

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith("farahdin-") && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("message", (event) => {
  if (event.data === "SKIP_WAITING") self.skipWaiting();
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  // Static assets: cache-first. URLs carry a content hash, so they never go stale.
  if (url.pathname.startsWith("/static/")) {
    event.respondWith(
      caches.match(req).then((hit) => hit || fetch(req).then((res) => {
        if (res.ok && (url.searchParams.has("v") || url.pathname.startsWith("/static/fonts/"))) {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => cache.put(req, copy));
        }
        return res;
      }))
    );
    return;
  }

  // Pages: always from the network (they are personal and fresh);
  // fall back to the offline page when the network is unavailable.
  if (req.mode === "navigate") {
    event.respondWith(fetch(req).catch(() => caches.match(OFFLINE_URL)));
  }
});
`))

func (a *App) serviceWorker(w http.ResponseWriter, r *http.Request) {
	precache := []string{
		"/offline",
		web.Asset("css/app.css"),
		web.Asset("js/app.js"),
		web.Asset("js/share-card.js"),
		web.Asset("js/htmx.min.js"),
		web.Asset("icons/sprite.svg"),
		web.Asset("icons/icon-192.png"),
		// Same URLs as in app.css, so the cache hit matches.
		"/static/fonts/javassoul.woff2",
		"/static/fonts/agaramond-sc.woff2",
		"/static/fonts/ebgaramond-regular.woff2",
	}
	list, _ := json.Marshal(precache)
	w.Header().Set("Content-Type", "text/javascript; charset=utf-8")
	w.Header().Set("Cache-Control", "no-cache")
	swTemplate.Execute(w, map[string]any{"Version": web.Version(), "Precache": string(list)})
}

// offline is precached by the service worker; it must not depend on a session.
func (a *App) offline(w http.ResponseWriter, r *http.Request) {
	response.Render(w, r, http.StatusOK, pages.Offline())
}

func (a *App) healthz(w http.ResponseWriter, r *http.Request) {
	ctx, cancel := context.WithTimeout(r.Context(), 2*time.Second)
	defer cancel()
	w.Header().Set("Cache-Control", "no-store")
	if err := a.DB.PingContext(ctx); err != nil {
		http.Error(w, "database unavailable", http.StatusServiceUnavailable)
		return
	}
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.Write([]byte("ok\n"))
}
